// This file will be generated by the Supabase CLI.
// npx supabase gen types typescript --project-id your-project-id > src/lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      // Placeholder for tables until generated
    }
    Views: {
      // Placeholder for views until generated
    }
    Functions: {
      // Placeholder for functions until generated
    }
  }
}
