
-- 1. Tabela de Perfis de Utilizador
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  total_points INTEGER DEFAULT 0,
  streak INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Qualquer um pode ver perfis" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Utilizadores podem atualizar o seu próprio perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Tabela de Progresso de Lições
CREATE TABLE IF NOT EXISTS public.user_lesson_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  lesson_id TEXT NOT NULL,
  level_id INTEGER NOT NULL,
  ka_id TEXT NOT NULL,
  lesson_type TEXT NOT NULL CHECK (lesson_type IN ('theory', 'exercise')),
  completed BOOLEAN DEFAULT true,
  last_code TEXT,
  quiz_score INTEGER,
  quiz_passed BOOLEAN,
  completed_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, lesson_id)
);

ALTER TABLE public.user_lesson_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Utilizadores veem o próprio progresso" ON public.user_lesson_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Utilizadores inserem o próprio progresso" ON public.user_lesson_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Utilizadores atualizam o próprio progresso" ON public.user_lesson_progress FOR UPDATE USING (auth.uid() = user_id);

-- 3. Função para Cálculo de Pontos (10 pontos por lição concluída)
CREATE OR REPLACE FUNCTION public.calculate_total_points(p_user_id UUID)
RETURNS VOID AS $$
DECLARE
  v_points INTEGER;
BEGIN
  SELECT COUNT(*) * 10 INTO v_points
  FROM public.user_lesson_progress
  WHERE user_id = p_user_id AND completed = true;

  UPDATE public.profiles
  SET total_points = v_points
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Trigger para atualização automática de pontos
CREATE OR REPLACE FUNCTION public.trigger_calculate_points()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM public.calculate_total_points(NEW.user_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS after_progress_change ON public.user_lesson_progress;
CREATE TRIGGER after_progress_change
AFTER INSERT OR UPDATE ON public.user_lesson_progress
FOR EACH ROW EXECUTE FUNCTION public.trigger_calculate_points();

-- 5. Tabela de Certificados
CREATE TABLE IF NOT EXISTS public.certificates (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  level_id INTEGER NOT NULL,
  level_title TEXT NOT NULL,
  issued_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Qualquer um pode verificar certificados" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Apenas o sistema pode emitir" ON public.certificates FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Comunidade (Fórum)
CREATE TABLE IF NOT EXISTS public.community_posts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  exercise_id TEXT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Ver posts" ON public.community_posts FOR SELECT USING (true);
CREATE POLICY "Criar posts" ON public.community_posts FOR INSERT WITH CHECK (auth.uid() = user_id);
